apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-flux-auth
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  source:
    path: services/auth_service/kustomize/
    repoURL: https://github.com/JesuFemi-O/flux-django.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true